ip_forward: true
log_commands: true

listeners:
  - query_port: 25577
    proxy_protocol: true
    max_players: 2020
    force_default_server: true
    priorities:
      - lobby

servers:
  # 公開サーバー
  lobby:
    motd: |2-
                 &4&nAzisaba Network&r &7[&a1.8.x-1.16.4&7]
              &fアジ鯖、たのしい。 &7| &oPowered by &bDDPS
    address: azisaba-lobby:25565
  lgw:
    address: azisaba-lgw:25565
  life:
    address: 192.168.100.208:49999
  sclat:
    address: azisaba-sclat:25565
  sclatsv1:
    address: azisaba-sclatsv1:25565
  sclatsv2:
    address: azisaba-sclatsv2:25565
  sclatsv3:
    address: azisaba-sclatsv3:25565
  sclatsv4:
    address: azisaba-sclatsv4:25565
  sclatsv5:
    address: azisaba-sclatsv5:25565
  sclatsv6:
    address: azisaba-sclatsv6:25565
  sclatsv7:
    address: azisaba-sclatsv7:25565
  sclatsv8:
    address: azisaba-sclatsv8:25565
  sclatsv9:
    address: azisaba-sclatsv9:25565
  sclatsv10:
    address: azisaba-sclatsv10:25565
  sclattest:
    address: azisaba-sclattest:25565
  sclattutorial1:
    address: azisaba-sclattutorial1:25565
  sclattutorial2:
    address: azisaba-sclattutorial2:25565
  sclattutorial3:
    address: azisaba-sclattutorial3:25565
  builders:
    address: azisaba-builders-lobby:25565
  builders12:
    address: azisaba-builders-12:25565
  builders15:
    address: azisaba-builders-15:25565
  builders16:
    address: azisaba-builders-16:25565

  # 鯖8
  parkour:
    address: 192.168.100.208:50001
  event:
    address: 192.168.100.208:50002
  rzh:
    address: 192.168.100.208:50003
  asterpvp:
    address: 192.168.100.208:50004
  chibi:
    address: 192.168.100.208:50005
  afk:
    address: 192.168.100.208:50006
  fsw:
    address: 192.168.100.208:50007
  lgwf:
    address: 192.168.100.208:50008
  coretol:
    address: 192.168.100.208:50009
  tsl:
    address: 192.168.100.208:50010
  lifebuild:
    address: 192.168.100.208:50011
  mts:
    address: 192.168.100.208:50012
  conquest:
    address: 192.168.100.208:50013
  rms:
    address: 192.168.100.208:50014
  jg24:
    address: 192.168.100.208:50015
  mkna:
    address: 192.168.100.208:50016
  coretol1build:
    address: 192.168.100.208:50020
  coretol1sv1:
    address: 192.168.100.208:50021
  coretol1sv2:
    address: 192.168.100.208:50022
  coretol1sv3:
    address: 192.168.100.208:50023
  coretol1sv4:
    address: 192.168.100.208:50024
  coretol1sv5:
    address: 192.168.100.208:50025
  coretol1sv6:
    address: 192.168.100.208:50026

  casino:
    address: 192.168.100.101:25565
  hh:
    address: 192.168.100.101:25566
  debug:
    address: 192.168.100.104:25565
